### PR TITLE
Whatif changes 1

### PR DESCRIPTION
**Pull request by AshbyMike**
Implements -whatif support for remove-tvdevice, remove-tvgroup, remove-tvgroupshare and updates help/description where added

### CODE REVIEW

**Comment by boivinx7** [comment]
Your on Fire

**Comment by boivinx7** [comment]
im trusting you on this, you can tell me once you feel that you are done with updates
Ill update the module on PS Gallery
https://www.powershellgallery.com/packages/TeamViewerPSModules

**Comment by AshbyMike** [comment]
You've just saved me deleting about 200 teamviewer groups, least I can do :-)

**Comment by boivinx7** [comment]
Thats a Lot of Groups... Must be a pain to manage the client deployment...

**Comment by AshbyMike** [comment]
We deploy via our RMM, which names the groups nicely, however our pre-existing groups now look messy 👍 so were doing some housekeeping at present!
I'll let you know when im done and ill get you to push an update once im done for the time being! Thanks!

**Comment by boivinx7** [comment]
Perfect

**Pull request merged**
